### ISSUE TITLE
Spurious Error

### ISSUE THREAD

**Issue by mdparker** [BindBC/bindbc-sfml#1]
With the official Windows binaries from sfml-dev.org, I'm getting a spurious error message when loading the Network library:

> Error: Missing Symbol, Msg: sfSocketSelector_wait 

The problem is that the symbol is definitely present in the DLL (I checked in Dependency Walker) and the function pointer is non-null after load (though I haven't yet found time to write enough of a program to test if it works).

I'll need to do some testing when I find some time, but in the interim, I'd be grateful if anyone can reproduce the issue and discover the cause.

**Comment by nak2yoshi** [comment]
https://github.com/BindBC/bindbc-sfml/blob/2536b07941b824e9be2355687afac8bfa8b00d7b/source/bindbc/sfml/graphics.d#L2166

🤔

**Comment by mdparker** [comment]
Ha. No wonder it's failing.

I should revise the error reporting in bindbc-loader to account for the library name. This wouldn't have been an issue had I realized it was coming from the graphics dll.

Thanks!
