### ISSUE TITLE
Calling `sfTransform_getMatrix` causes program to crash

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#12]
I have the following code:

```D
sfTransform t = sfTransform_fromMatrix(
    5, 5, 5,
    4, 4, 4,
    3, 3, 3
);

float mtrx;

sfTransform* t_ptr = &t;
t_ptr.sfTransform_getMatrix(&mtrx);
```

Upon running the app, I get the following error and a black screen:

```
Program exited with code -11
```

This seems to be an issue in the bindings as I am doing everything according to the documentation.

**Comment by ichordev** [comment]
If you’re using dynamic bindings then make sure those two function pointers aren’t null.
Otherwise you’re going to have to investigate with a debugger to at least determine which of those functions caused the segfault, because a segfault is just a generic memory access violation.

**Comment by therealbluepandabear** [comment]
I will investigate and come back to you thanks.
