### ISSUE TITLE
No `sfEvtSensorChanged` in `sfEventType`?

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#13]
Hey,

The `sfEventType` enum does not contain `sfEvtSensorChanged`, which is implemented in CSFML:

https://github.com/SFML/CSFML/blob/ea8048376f19fb74666a18e734b8fdc3ecf1f7bc/include/SFML/Window/Event.h

![image](https://user-images.githubusercontent.com/50536495/214762650-0494ffa2-76e3-47d2-8cec-b740038196eb.png)

If it is actually `sfEvtTouchChanged`, could you please rename it to what CSFML uses, as it is currently very confusing.

Regards,
thebluepandabear

**Comment by ichordev** [comment]
Seems to be a naming error. Please submit a PR for this. ;)

**Comment by therealbluepandabear** [comment]
OK .
