### ISSUE TITLE
App shouldn't require older `.so` files to run

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#15]
Hey, apologies for the issue spammin

I recently did a fresh install of CSFML and I am getting this errors when running the program:

```
object.Exception@source/app.d(38): Fatal error(s) encountered whilst calling `loadSFML()` function: ["Error: libcsfml-system.so, Message: libsfml-system.so.2.5: cannot open shared object file: No such file or directory", "Error: libcsfml-system.so.2, Message: libcsfml-system.so.2: cannot open shared object file: No such file or directory", "Error: libcsfml-system.so.2.0, Message: libcsfml-system.so.2.0: cannot open shared object file: No such file or directory"]
```

I don't know why the app is requiring for outdated `.so.2.0` (version 2) files to be installed on the system, I only seem to have `.so` and `.so.2.5` and `.so.2.5.0`. Could you perhaps change the requirements to match the latest CSFML version?

**Comment by ichordev** [comment]
Normally there *should* be symlinks for those. You can [make your own symlinks](https://stackoverflow.com/questions/1951742/how-can-i-symlink-a-file-in-linux) if you want, or you could add those differently named libraries to `libNames` in the `loadSFML[module name]` functions in each module. (e.g. [here](https://github.com/BindBC/bindbc-sfml/blob/master/source/bindbc/sfml/audio.d#L545) in `audio.d`)

Also do you know why your error message says "Error: libcsfml-system.so, Message: libsfml-system.so.**2.5**"? If your object file is really named ".so.2.5" it sounds like it should be loading in this case.

**Comment by therealbluepandabear** [comment]
Yeah Man... It's weird. I think it's cause I played around too much and deleted some stuff, I was forced to reinstall CSFML, everything kind of went bad. But now it should be good as I removed each package and reinstalled from scratch.

I do have the `.so.2.5` packages:

![image](https://user-images.githubusercontent.com/50536495/215269125-98c1ca6b-e6ec-47b8-91bf-0c1cd48ee950.png)

I do not know why its not detecting them. I will look into the symlinks and see if that will fix it.

**Comment by ichordev** [comment]
> ![image](https://user-images.githubusercontent.com/50536495/215269125-98c1ca6b-e6ec-47b8-91bf-0c1cd48ee950.png)

Ah I see there you have symlinks already for `.so` with no extension, as it should be. Any idea why they're green? Perhaps they're pointing to an invalid location, have you tried checking what they point to? (You can usually do this by right clicking on them in a file browser)

**Comment by therealbluepandabear** [comment]
> > ![image](https://user-images.githubusercontent.com/50536495/215269125-98c1ca6b-e6ec-47b8-91bf-0c1cd48ee950.png)
> 
> Ah I see there you have symlinks already for `.so` with no extension, as it should be. Any idea why they're green? Perhaps they're pointing to an invalid location, have you tried checking what they point to? (You can usually do this by right clicking on them in a file browser)

They've (the .so files) always been green.

An important detail I didn't say is that they used to appear in the `/usr/local/lib` directory, but now they just appear in the `/usr/lib/gnulinuxblahblah` directory (as you can see in the image). 

Right clicking on the file just opens up the menu for the settings, but here's more info:

![image](https://user-images.githubusercontent.com/50536495/215269762-0f14a011-a7d5-4c41-8a07-64a03d1280d5.png)

But yeah it's honestly very weird, I didn't expect it to be such a pain to configure csfml.

**Comment by ichordev** [comment]
> An important detail I didn't say is that they used to appear in the `/usr/local/lib` directory, but now they just appear in the `/usr/lib/gnulinuxblahblah` directory (as you can see in the image).

`/usr/local/lib` is for libraries you built and installed yourself, hence "local".
So they're in `/usr/lib/x86_64-linux-gnu` I assume? Could you check `/etc/ld.so.conf` and each of the files in `/etc/ld.so.conf.d/` to see if any of them have that path in them? If not, you might want to add such a file:
```conf
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

**Comment by therealbluepandabear** [comment]
Hey - Just Woke Up,

First of all just wanted to say I truly appreciate the fact that you are helping me with this.

In `ld.so.conf` I have the following text:

`include /etc/ld.so.conf.d/*.conf`

In the `/etc/ld.so.conf.d` folder it does seem like I have that 'linux-gnu' path:

![image](https://user-images.githubusercontent.com/50536495/215297022-a8eabaab-e92b-4400-8fa4-1e25c153c81d.png)

In the `x86-64-linux-gnu.conf` file I have that exact text:

![image](https://user-images.githubusercontent.com/50536495/215297081-17ebd329-8127-4668-aab2-2d238add5455.png)

**Comment by therealbluepandabear** [comment]
Btw  I know it is off topic but can you please make a new release after that fix I did.

**Comment by therealbluepandabear** [comment]
I redid everything on a brand new virtual machine: Same problem.

**Comment by marcusmueller** [comment]
Can't reproduce. 

Tried to reproduce this. I'm not a D programmer, at all, I just copied and pasted the JSON from the bindbc-sfml Readme.md into dub.json, and did nothing but try loading SFML:
[Minimal test project](https://github.com/marcusmueller/DLang-Demo/)

Relevant D code:
```D
import std.stdio;
import bindbc.sfml;
void main()
{
	if(!loadSFML()) {
		writeln("Can't load CSFML");
	}
	else {
		writeln("loaded CSFML.");
	}
}
```

What I did as setup: (Replace `podman` with `docker` if you prefer that):
```shell
podman run --pull newer --rm -it linuxmintd/mint21.1-amd64
root@2431e18ad66a:/# apt install -y libcsfml-dev dub git
  [successful apt output]
root@2431e18ad66a:/# git clone https://github.com/marcusmueller/DLang-Demo
  [successful git clone output]
root@2431e18ad66a:/# cd DLang-Demo/
root@2431e18ad66a:/DLang-Demo# dub
Fetching bindbc-sfml 1.0.2 (getting selected version)...
Fetching bindbc-loader 1.0.1 (getting selected version)...
Performing "debug" build using /usr/bin/ldc2 for x86_64.
bindbc-loader 1.0.1: building configuration "noBC"...
bindbc-sfml 1.0.2: building configuration "dynamic"...
proj ~main: building configuration "application"...
Linking...
Running proj
loaded CSFML.
```
Result: Loading just works.

**Comment by ichordev** [comment]
> Can't reproduce.

Your package is using SFML 2.0 not SFML 2.5. Also was this done on Fedora? therealbluepanda is using a Debian-based distro IIRC, and it seems to only have packages for CSFML 2.5 which is missing a critical bugfix from CSFML 2.5.1

**Comment by marcusmueller** [comment]
There's no CSFML 2.0 on my system; only 2.5 :)  So, no. It's not using SFML 2.0. How would you even see that from the output?

> Also was this done on Fedora?

No, inside a Linux Mint 21.1 container, see my setup! (How would I run `apt` on Fedora?)

As that is exactly the platform therealbluepanda [is using](https://unix.stackexchange.com/questions/733561/sfml-csml-libsfml-system-so-2-5-cannot-open-shared-object-file). The Linux Mint doesn't "see" anything about my host operating system – this is a container.

**Comment by marcusmueller** [comment]
Just to illustrate:

```shell
strace -o mytrace.strace ./proj
```

generates a beautiful strace log, and inside that you see the dynamic loader properly loading libsfml-graphics.so.2.5:

```strace
…
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libsfml-graphics.so.2.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340\363\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=326384, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 329552, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fdb638ea000
…
```

**Comment by marcusmueller** [comment]
If there's something to modify in that project to reproduce, please, @ichordev, @therealbluepandabear, let me know. The point of it really is just to isolate the failure.

**Comment by ichordev** [comment]
> There's no CSFML 2.0 on my system; only 2.5 :) So, no. It's not using SFML 2.0. How would you even see that from the output?

Then you installed the wrong version of the library for your package. You didn't put version identifier `SFML_205` so the bindings are expecting SFML 2.0, which is the default. If you try to use functions which have different symbols between 2.0 and 2.5 you will probably get a segfault.

**Comment by mdparker** [comment]
> Then you installed the wrong version of the library for your package. You didn't put version identifier SFML_205 so the bindings are expecting SFML 2.0, which is the default.

The whole point of the dynamic binding is that, as long as there's API compatibility, an older version of the API can be loaded from newer libraries. So you can load 2.0 from 2.5 libraries just fine. That's why the binding has a list of library names to attempt to load.

**Comment by marcusmueller** [comment]
@ichordev Though this already definitely shows that the files *can* be found on Mint21.1, so the error message @therealbluepandabear sees is … dubious.

Anyways, please do recheck my dub.json; I just added the `SFML_205` version as you said. Still same scenario: can't reproduce any problem.

**Comment by mdparker** [comment]
@therealbluepandabear 
> I don't know why the app is requiring for outdated .so.2.0 (version 2) files to be installed on the system

It doesn't require that library version. The loader attempted to find the libraries listed in the error message in order you see them. When 2.5 failed to load, it attempted to load .2.5, then .2 then .2.0. It couldn't find any of them. That means none of them are on your default library search path.

**Comment by marcusmueller** [comment]
@ichordev HA! can reproduce. As soon as I fix your `SFML_205` typo to be `SFML_250`, and do a clean rebuild, it can't load CSFML anymore. 

Interestingly, `strace` (attaching full output) still shows that the program correctly looks for libsfml-\*.so.2.5, opens them, mmap's them, but `loadSFML()` still seems to return a falsey value.

@mdparker it would seem there's something fishy going on with the dynamic loading, then!

**Comment by mdparker** [comment]
@marcusmueller Can you be more specific about the value being returned? Thanks!

**Comment by marcusmueller** [comment]
@mdparker honestly, having a hard time. the `if(!loadSFML())` branch is taken.

And I think I know what's wrong: I followed the Readme.md example, which says:

https://github.com/BindBC/bindbc-sfml/blob/f736abb9f55a7d623bab3f33c74a38fdbf817314/README.md?plain=1#L107-L111

Notice `250`, which I thought was *right* and that `205` was a typo in @ichordev's comment. Turns out, it's the other way around: `205` is the right number, and with that it works.

Now, that again makes the problem irreproducible.

**Comment by ichordev** [comment]
> [strace.txt](https://github.com/BindBC/bindbc-sfml/files/10529974/strace.txt) @ichordev HA! can reproduce. As soon as I fix your `SFML_205` typo to be `SFML_250`, and do a clean rebuild, it can't load CSFML anymore.

Oh huh apparently that's an issue with the docs. :grimacing:

**Comment by mdparker** [comment]
Geez. It's been so long since I looked at this stuff. I always forget `loadSFML` returns a Boolean since it wraps all the more specific loaders.

**Comment by marcusmueller** [comment]
> Oh huh apparently that's an issue with the docs. grimacing

So, which is right?

**Comment by ichordev** [comment]
> @mdparker honestly, having a hard time. the `if(!loadSFML())` branch is taken.
> 
> And I think I know what's wrong: I followed the Readme.md example, which says:
> 
> https://github.com/BindBC/bindbc-sfml/blob/f736abb9f55a7d623bab3f33c74a38fdbf817314/README.md?plain=1#L107-L111
> 
> Notice `250`, which I thought was _right_ and that `205` was a typo in @ichordev's comment. Turns out, it's the other way around: `205` is the right number, and with that it works.
> 
> Now, that again makes the problem irreproducible.

SFML_205 is incorrect, SFML_250 is correct: https://github.com/BindBC/bindbc-sfml/blob/master/source/bindbc/sfml/config.d#L24

**Comment by mdparker** [comment]
> SFML_205 is incorrect, SFML_250 is correct

Yes. All of the versions listed in the docs are wrong.

**Comment by ichordev** [comment]
Except the versions that are in that broken table. Lemme fix that

**Comment by marcusmueller** [comment]
Great, then I can reproduce the problem using `SFML_250`! (I mean, debatable whether "great", but still, a reproducible bug is better than none).

Two things:

- I can now reproduce. Great! We have no idea whether that actually is the same problem @therealbluepandabear has – we don't know whether they do `"versions": ["SFML_250"]` at all. I guess we'll have to see *their* failing use case
- I can definitely *not* reproduce the error message as @therealbluepandabear sees it. And as we basically all agree, the libraries should be found (and they're found very well on my Mint 21.1).

Forward step?

**Comment by therealbluepandabear** [comment]
> Great, then I can reproduce the problem using `SFML_250`! (I mean, debatable whether "great", but still, a reproducible bug is better than an irreproducible one).
> 
> Two things:
> 
> * I can now reproduce. Great! We have no idea whether that actually is the same problem @therealbluepandabear has – we don't know whether they do `"versions": ["SFML_250"]` at all. I guess we'll have to see _their_ failing use case
> * I can definitely _not_ reproduce the error message as @therealbluepandabear sees it. And as we basically all agree, the libraries should be found (and they're found very well on my Mint 21.1).
> 
> Forward step?

Hey,

The reason you can't reproduce it is because you didn't 'observe' the errors -- copy and paste this function:

```D
import bindbc.loader;
import std.conv;

void loadDyn() {
	if (!loadSFML()) {
		string[] messages;

		foreach (const(ErrorInfo) err; errors) {
			string errorStr = to!string(err.error);
			string messageStr = to!string(err.message);

			messages ~= format("Error: %s, Message: %s", errorStr, messageStr);
		}

		throw new Exception(format("Fatal error(s) encountered whilst calling `loadSFML()` function: %s", messages));
	}
}

void main() {
	loadDyn();
        ...
}
```

If that doesn't show you any output similar to what I had, then you are most definitely getting a different error.

I do have the `"versions": ["SFML_250"]` -- changing it `"versions": ["SFML_205"]` does nothing on my end to fix this.

**Comment by marcusmueller** [comment]
Honestly, this is github, and we're trying to narrow down *your* issue: can you do this on a fork of my repo yourself? The D code I wrote for this example is my first ever D, and honestly, this says that this is the point where I leave this in your able hands – especially since [this](https://github.com/BindBC/bindbc-sfml/issues/15#issuecomment-1407666356) comment contains a complete minimal reproducible isolated operating system environment, with which you can test :)

**Comment by therealbluepandabear** [comment]
> Honestly, this is github, and we're trying to narrow down _your_ issue: can you do this on a fork of my repo yourself? The D code I wrote for this example is my first ever D, and honestly, this says that this is the point where I leave this in your able hands – especially since [this](https://github.com/BindBC/bindbc-sfml/issues/15#issuecomment-1407666356) comment contains a complete minimal reproducible isolated operating system environment, with which you can test :)

All right. It's your repo, your choice.

**Comment by therealbluepandabear** [comment]
I think I have made a big mess of this issue, and it's best not to drag people here on GitHub into my problems. 

I've asked a question on StackOverflow about this, so I don't think there's much need to continue this issue request.

It's embarrassing to be in this position.

Next time I'll try to solve stuff on my own instead of bugging everyone, apologies.
