### ISSUE TITLE
run crash

### ISSUE THREAD

**Issue by lilijreey** [BindBC/bindbc-sfml#16]
![image](https://github.com/BindBC/bindbc-sfml/assets/1732373/20d9b268-02b7-4ebf-b0d9-0871d2479789)
dub json 
dmd + ubuntu 22.04
```
{
        "authors": [
                "god"
        ],
        "copyright": "Copyright © 2023, god",
        "dependencies": {
                "bindbc-sfml": "~>1.0.0"
        },
        "versions": [
                "BINDSFML_Static",
                "SFML_Audio",
                "SFML_Graphics",
                "SFML_250"

        ],
        "libs":["csfml-graphics", "csfml-audio"],
        "description": "A minimal D application.",
        "license": "proprietary",
        "name": "dmap"
}
```

**Comment by ichordev** [comment]
Hey, I’m pretty sure version identifiers are case-sensitive. (the spec doesn’t say otherwise, at least)
Please use `BindSFML_Static`, otherwise you will have to load the shared library with `loadSFML`.

**Comment by ichordev** [comment]
Oops, pressed the wrong button!

**Comment by lilijreey** [comment]
> Hey, I’m pretty sure version identifiers are case-sensitive. (the spec doesn’t say otherwise, at least) Please use `BindSFML_Static`, otherwise you will have to load the shared library with `loadSFML`.

Delete SFML_250 is ok.

**Comment by ichordev** [comment]
> Delete SFML_250 is ok.

What SFML version do you have installed?

**Comment by lilijreey** [comment]
> > Delete SFML_250 is ok.
> 
> What SFML version do you have installed?

2.5
![image](https://github.com/BindBC/bindbc-sfml/assets/1732373/869943ed-9165-4d6f-a11a-af8926c15cb6)

**Comment by lilijreey** [comment]
I have suggest for the api define,  export api function name is create batter than XXX_create, because D is OO, user can be used UCFY call it, look like OO. example:
![image](https://github.com/BindBC/bindbc-sfml/assets/1732373/fab29faf-a37e-4954-a6a0-2c322868cfd5)

we can call
```
 auto view = psfView_create();
view.setSize(xxx), better than view.psfView_setSize(xxx)

**Comment by ichordev** [comment]
> I have suggest for the api define, export api function name is create batter than XXX_create, because D is OO, user can be used UCFY call it, look like OO. example: ![image](https://user-images.githubusercontent.com/1732373/250228714-fab29faf-a37e-4954-a6a0-2c322868cfd5.png)
> 
> we can call
> 
> ```
>  auto view = psfView_create();
> view.setSize(xxx), better than view.psfView_setSize(xxx)
> ```

These are *bindings* to SFML’s C API, which is a C API. It is not a wrapper. If you want to create an OO wrapper, or use an existing one made by someone else then feel free. At some point these bindings might be rewritten to bind the SFML C++ API, but it’s not super high on my priority list right now, as these bindings are pretty stable and I’d like to wait for SFML3.

**Comment by lilijreey** [comment]
ok
