### ISSUE TITLE
Incorrect signature of sfShader_createFromFile

### ISSUE THREAD

**Issue by ramillies** [BindBC/bindbc-sfml#3]
In CSFML 2.5.1, the function `sfShader_createFromFile` has the following signature:

    sfShader* sfShader_createFromFile(const char* vertexShaderFilename, const char* geometryShaderFilename, const char* fragmentShaderFilename);

(see [the CSFML sources](https://github.com/SFML/CSFML/blob/master/include/SFML/Graphics/Shader.h#L60)), but in this module, the function is declared only with two parameters:

    sfShader* sfShader_createFromFile(const(char)* vertexShaderFilename, const(char)* fragmentShaderFilename);

This results either in a compiler error (if the user tries to use the correct three-argument call according to the CSFML docs), or in a mysterious crash as soon as the function is called (if they try to use the two-argument call).

**Comment by mdparker** [comment]
Thanks. The third parameter was added in csfml 2.4 to all three forms of the shader creation function, but I only caught one of them and only for the static binding. Now they should all three be correct in both the static and dynamic bindings.

I also took this opportunity to tag a 1.0.0 release, meaning it's now dependent on bindbc-loader 1.0.x.
