### ISSUE TITLE
libcsfml-system.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#6]
Hello,

I am getting the following error trying to run this library:

```
"Error: libcsfml-system.so, Message: libcsfml-system.so: cannot open shared object file: No such file or directory",
```

This is my code:

```D
import std.stdio;
import bindbc.sfml;
import bindbc.loader;
import std.string;
import std.conv;

import loader = bindbc.loader.sharedlib;

void loadDyn() {
	if (!loadSFML()) {
		string[] messages;

		foreach (const(ErrorInfo) err; loader.errors) {
			string errorStr = to!string(err.error);
			string messageStr = to!string(err.message);

			messages ~= format("Error: %s, Message: %s", errorStr, messageStr);
		}

		throw new Exception(format("Fatal error(s) encountered whilst calling `loadSFML()` function: %s", messages));
	}
}

void main() {
	loadDyn();

	sfContextSettings* settings;
	sfRenderWindow* window = sfRenderWindow_create(sfVideoMode(600, 300), "Hi", sfWindowStyle.sfNone, settings);

	while (window.sfRenderWindow_isOpen()) {
		sfEvent* event;

		while (window.sfRenderWindow_pollEvent(event)) {
			if (event.type == sfEventType.sfEvtClosed) {
				window.sfRenderWindow_close();
			}
		}

		window.sfRenderWindow_clear(sfBlack);

		window.sfRenderWindow_display();
	}
}

```

I was wondering how I would go around fixing this error?

Thanks.

**Comment by mdparker** [comment]
The error means the loader can't find CSFML's system shared library on your system. Did you install CSFML? If so, where are the shared libraries installed?

**Comment by therealbluepandabear** [comment]
> The error means the loader can't find CSFML's system shared library on your system. Did you install CSFML? If so, where are the shared libraries installed?

Hello,

I just installed CSFML using `sudo apt-get install csfml-dev`, but now I am getting a new error:

`
object.Exception@source/app.d(20): Fatal error(s) encountered whilst calling `loadSFML()` function: ["Error: Missing Symbol, Message: sfRenderTexture_createWithSettings", "Error: Missing Symbol, Message: sfRenderTexture_getMaximumAntialiasingLevel", "Error: Missing Symbol, Message: sfText_getLineSpacing", "Error: Missing Symbol, Message: sfText_getLineSpacing"]
`

Regards,
thebluepandabear

**Comment by mdparker** [comment]
Look closely at the error message. It's telling you that the loader found the library, but specific symbols it expected to find aren't there. The first one in the list is `sfRenderTexture_createWithSettings`. That is from CSFML 2.5. So what that tells me is that you've configured the binding to load 2.5, but the shared library on your system is a lower version. 

In your code, you have this line:

```
if (!loadSFML())
```

`loadSFML` returns an enum value that will tell you which version of the library the loader found on your system. There's an example in the README that uses it to test for different error conditions. Anyway, here's something that's more robust than what you have now:

```
auto ret = loadSFML();
if(ret == SFMLSupport.noLibrary) {
    // The loader didn't find one ore more CSFML libraries
    ...
}
else if(ret == SFMLSupport.badLibrary) {
    // The loader found the libraries, but it was unable to load the version we expected. Maybe one or more of the libraries 
    // are corrupt, but more likely it they're just a lower version.
    ...
}
```

To handle the `badLibrary` case, you there are functions to check which version of each library was loaded: `loadedSFMLSystemVersion`, `loadedSFMLGraphicsVersion`, etc. Printing the return values will tell you which version is installed on your system. If you don't need any specific functions from later versions, then you can configure the binding to use that version instead. Otherwise, you'll have to find another way to install the CSFML libraries.

It's common for the official package managers on Linux distros that don't have rolling releases to be behind the latest release of specific libraries.

And for the record, you don't need the `-dev` version of any libraries when using the dynamic bindings. The `-dev` versions install header files and static libraries that the binding doesn't need. All you need are the shared libraries, and those are installed by the non `-dev` packages.

**Comment by therealbluepandabear** [comment]
> `loadedSFMLSystemVersion`

Hey thanks, I found out that the SFML graphics has a lower version of 240:

`SYSTEM VERSION: sfml250, GRAPHICS VERSION: sfml240`

How would I go around upgrading the graphics to use the latest version?

**Comment by mdparker** [comment]
Alright. So, when I said the `loaded*Version` functions would tell you which version of the library is installed, that's only true when there are no other issues. What happens is, the loader will first load all of the functions of the lowest supported version, then the next, then the next, and so on, and will set an internal variable indicating the highest version it successfully loaded. That's the value returned by `loaded*Version`. 

Usually, a failure to load the configured version is because a lower version of the C library is installed (as in, you've asked for 2.5, but only have 2.4 installed). But that's not always the case. It could also be because there's a bug in the binding, or because the shared library was compiled without support for specific functions, or maybe the shared library has somehow become corrupt.

So, back to your specific case. Though it's possible that a CSFML apt package would bundle one version of the CSFML graphics library and another version of everything else seems rather unlikely. CSFML 2.5 means 2.5 of everything. And looking at the official apt repository lists, they show the package has 2.5 of everything. You could verify this by looking for the shared libraries on your system, but there's no need. I'm sure you have 2.5 installed.

You've listed three missing symbols (`sfText_getLineSpacing` was printed twice). As you can see in the binding's source, there are several more functions loaded from the CSFML graphics lib than those:

https://github.com/BindBC/bindbc-sfml/blob/master/source/bindbc/sfml/graphics.d#L2431

If none of those other functions are showing up in the error output, that means the loader was able to find them. So the reason you can only load up to 2.4 of the graphics library lies somewhere else.

My first thought at this stage would be to look for a bug in the binding. Perhaps the function names are misspelled. But that's not the case. Everything is spelled correctly.

So my next thought would be to check the shared library. Maybe the build was misconfigured so that the missing functions weren't properly exported.

But at this point, I all I can do is guess.

**Comment by therealbluepandabear** [comment]
No worries, I understand that there is little you can do due to the complexity of the issue. 

I will ask a question on StackOverflow as to how I can get around this issue.

Hopefully this gets fixed in the future! I'll still use these bindings as it seems as though 2.4 has all that I need.

**Comment by ichordev** [comment]
Was this issue resolved yet?

**Comment by therealbluepandabear** [comment]
> Was this issue resolved yet?

No, unfortunately. The issue seems quite complex, I do not know the cause of it. It is either an issue with the package itself  (which I doubt), the bindings, or something on my end. 

Are you able to reproduce this? I am running Linux.

**Comment by ichordev** [comment]
> No, unfortunately. The issue seems quite complex, I do not know the cause of it. It is either an issue with the package itself (which I doubt), the bindings, or something on my end.
> 
> It's frustrating as I am stuck with CSFML 2.4.
> 
> Are you able to reproduce this? I am running Linux.

I have not tried to reproduce it but I suspect it's an issue on your end specifically.
Here's a few things you could tell me so I can help you get to the bottom of this:

- What's your Linux distro & version?
- Did you install the dynamic library (`libcsfml`, *NOT* `libcsfml-dev`) via your package manager?
  - If yes: Are you sure that your package manager gave you version 2.5 not 2.4?
  - If no: Where did you install it manually? Have you made sure that your package manager hasn't also downloaded `libcsfml` as a dependency to something else?

**Comment by therealbluepandabear** [comment]
> > No, unfortunately. The issue seems quite complex, I do not know the cause of it. It is either an issue with the package itself (which I doubt), the bindings, or something on my end.
> > It's frustrating as I am stuck with CSFML 2.4.
> > Are you able to reproduce this? I am running Linux.
> 
> I have not tried to reproduce it but I suspect it's an issue on your end specifically. Here's a few things you could tell me so I can help you get to the bottom of this:
> 
>     * What's your Linux distro & version?
> 
>     * Did you install the dynamic library (`libcsfml`, _NOT_ `libcsfml-dev`) via your package manager?
>       
>       * If yes: Are you sure that your package manager gave you version 2.5 not 2.4?
>       * If no: Where did you install it manually? Have you made sure that your package manager hasn't also automatically downloaded `libcsfml` as a dependency to something else?

# Answers for of your questions

1. I am running Linux Mint 21 (Ubuntu Jammy, Debian based), Linux kernel version 5.15.0-56-generic x86_64

2. Typing in `sudo apt-get install libcsfml` gives me the following in the terminal:

![image](https://user-images.githubusercontent.com/50536495/207987214-58ddafbd-15e7-45c3-8e5b-5bab6d3ec416.png)

As you can see, the package does not exist.  

**I specifically installed the libcsfml-dev package, I am not aware of any other way of getting libcsfml.**

I am 99.9% sure I have CSFML 2.5 installed, I've looked through the header files and found functions that have been added only in version 2.5.

Calling the following in my application:

```D

**Comment by ichordev** [comment]
> 1. I am running Linux Mint 21 (Ubuntu Jammy, Debian based), Linux kernel version 5.15.0-56-generic x86_64
> 
> 2. Typing in `sudo apt-get install libcsfml` gives me the following in the terminal:

These should be the CSFML packages on your distro:
```
[libcsfml-audio2.5](https://packages.ubuntu.com/jammy/libs/libcsfml-audio2.5) (2.5-1.1) [universe]
    Libraries for the C Binding of SFML - Audio Part
[libcsfml-graphics2.5](https://packages.ubuntu.com/jammy/libs/libcsfml-graphics2.5) (2.5-1.1) [universe]
    Libraries for the C Binding of SFML - Graphics Part
[libcsfml-network2.5](https://packages.ubuntu.com/jammy/libs/libcsfml-network2.5) (2.5-1.1) [universe]
    Libraries for the C Binding of SFML - Network Part
[libcsfml-system2.5](https://packages.ubuntu.com/jammy/libs/libcsfml-system2.5) (2.5-1.1) [universe]
    Libraries for the C Binding of SFML - System Part
[libcsfml-window2.5](https://packages.ubuntu.com/jammy/libs/libcsfml-window2.5) (2.5-1.1) [universe]
```

> **I specifically installed the libcsfml-dev package,**

You're using dynamic bindings, so `libcsfml-dev` is irrelevant.

> **I am not aware of any other way of getting libcsfml.**

You can compile and install it yourself from source, but it's probably not going to be necessary. Soing so without uninstalling the version from your package manager could cause the exact problem you're currently having.

> I've looked through the header files and found functions that have been added only in version 2.5.
> 
> E.g., `sfVertexBuffer` **was added in version 2.5** and I can find it in /usr/include/SFML/Graphics:

If you know where the header files are, try looking in the same outer-directory but under `lib` instead of `include`.
For instance, `/usr/local/include/SFML` => `/usr/local/lib/SFML`. If they're not there, try using a search feature to find "sfml" in `/usr`.
If you find the `.so` files, try reading the symbols they contain by using `nm -gD <filename>` and make sure that those symbols also include the names of those functions added in 2.5.

> For some reason or another your library is only loading version 240 of CSFML graphics (or maybe it's just telling me that it has but it's invalid??), I can't tell you why specifically, but that's the error I've observed.
> 
> **If I don't observe any of the errors in the `loadDyn()` function, it's not fatal, I am still able to use the library fine.**
> 
> I'm not sure how valid the output is because I am still able to access the following functions (not sure if they work):

Yes, that is pretty weird. Have you checked the result of `bindbc.loader.errors()`?

**Comment by therealbluepandabear** [comment]
Thanks for the package links.

I think `csfml-dev` simply includes those packages, as when I type in `sudo apt-get install {package}` I get the following output:

![image](https://user-images.githubusercontent.com/50536495/208190081-b137e44c-b98c-4596-a2db-6f3b59b2709d.png)

I get the same output (saying it's already installed) with all the other packages mentioned. I do not believe I have installed `csfml` incorrectly (although I may be wrong).

I'm not sure what you mean by saying `libcsfml-dev` is irrelevant, if I remove it, then nothing runs lol.

Looking through `/usr/local/lib/SFML`, I get the following files:

```
cmake                       libraylib.so.4.2.0
libcsfml-audio.so           libraylib.so.420
libcsfml-audio.so.2.2       libsfml-audio.so
libcsfml-audio.so.2.2.0     libsfml-audio.so.2.2.0
libcsfml-graphics.so        libsfml-audio.so.2.5
libcsfml-graphics.so.2.2    libsfml-audio.so.2.5.1
libcsfml-graphics.so.2.2.0  libsfml-graphics.so
libcsfml-network.so         libsfml-graphics.so.2.2.0
libcsfml-network.so.2.2     libsfml-graphics.so.2.5
libcsfml-network.so.2.2.0   libsfml-graphics.so.2.5.1
libcsfml-system.so          libsfml-network.so
libcsfml-system.so.2.2      libsfml-network.so.2.2.0
libcsfml-system.so.2.2.0    libsfml-network.so.2.5
libcsfml-window.so          libsfml-network.so.2.5.1
libcsfml-window.so.2.2      libsfml-system.so
libcsfml-window.so.2.2.0    libsfml-system.so.2.2.0
libGLEW.a                   libsfml-system.so.2.5
libGLEWmx.a                 libsfml-system.so.2.5.1
libGLEWmx.so                libsfml-window.so
libGLEWmx.so.1.10           libsfml-window.so.2.2.0
libGLEWmx.so.1.10.0         libsfml-window.so.2.5
libGLEW.so                  libsfml-window.so.2.5.1
libGLEW.so.1.10             node_modules
libGLEW.so.1.10.0           pkgconfig
libraylib.so                python3.10
```

It seems like all the newest library versions have been installed.

Running your command on `libsfml-window.so.2.5.1` produces a mostly unreadable format, but since it has the version name '2.5.1' I am assuming that it is the newest version. I can prove this because I can find text containing `VertexBuffer` which was added in 2.5.1, e.g.:

![image](https://user-images.githubusercontent.com/50536495/208191326-7ffcaa1f-241b-4879-bc18-c7b98d171ac8.png)

In conclusion, I am confident that I have the newest version on my system.

Now, when it comes to errors, I have the following function to assist me with error output:

```D
void loadDyn() {
	if (!loadSFML()) {
		string[] messages;

		foreach (const(ErrorInfo) err; loader.errors) {
			string errorStr = to!string(err.error);
			string messageStr = to!string(err.message);

			messages ~= format("Error: %s, Message: %s", errorStr, messageStr);
		}

		throw new Exception(format("Fatal error(s) encountered whilst calling `loadSFML()` function: %s", messages));
	}
}
```

Running the function, I get the following output:

```
object.Exception@source/app.d(22): Fatal error(s) encountered whilst calling `loadSFML()` function: ["Error: Missing Symbol, Message: sfRenderTexture_createWithSettings", "Error: Missing Symbol, Message: sfRenderTexture_getMaximumAntialiasingLevel", "Error: Missing Symbol, Message: sfText_getLineSpacing", "Error: Missing Symbol, Message: sfText_getLineSpacing"]
```

As I said before, these errors aren't fatal.

Not sure what the next steps are in solving this.

**Comment by ichordev** [comment]
> I think `csfml-dev` simply includes those packages

Not quite, they're dependencies.
> 
> ![image](https://user-images.githubusercontent.com/50536495/208190081-b137e44c-b98c-4596-a2db-6f3b59b2709d.png)
> 
> I get the same output (saying it's already installed) with all the other packages mentioned. I do not believe I have installed `csfml` incorrectly (although I may be wrong).

Take note of how it says "lib**c**sfml-audio**2.5**"—that will be important.

> Looking through `/usr/local/lib/SFML`, I get the following files:
> 
> ```
> cmake                       libraylib.so.4.2.0
> libcsfml-audio.so           libraylib.so.420
> libcsfml-audio.so.2.2       libsfml-audio.so
> libcsfml-audio.so.2.2.0     libsfml-audio.so.2.2.0
> libcsfml-graphics.so        libsfml-audio.so.2.5
> libcsfml-graphics.so.2.2    libsfml-audio.so.2.5.1
> libcsfml-graphics.so.2.2.0  libsfml-graphics.so
> libcsfml-network.so         libsfml-graphics.so.2.2.0
> libcsfml-network.so.2.2     libsfml-graphics.so.2.5
> libcsfml-network.so.2.2.0   libsfml-graphics.so.2.5.1
> libcsfml-system.so          libsfml-network.so
> libcsfml-system.so.2.2      libsfml-network.so.2.2.0
> libcsfml-system.so.2.2.0    libsfml-network.so.2.5
> libcsfml-window.so          libsfml-network.so.2.5.1
> libcsfml-window.so.2.2      libsfml-system.so
> libcsfml-window.so.2.2.0    libsfml-system.so.2.2.0
> libGLEW.a                   libsfml-system.so.2.5
> libGLEWmx.a                 libsfml-system.so.2.5.1
> libGLEWmx.so                libsfml-window.so
> libGLEWmx.so.1.10           libsfml-window.so.2.2.0
> libGLEWmx.so.1.10.0         libsfml-window.so.2.5
> libGLEW.so                  libsfml-window.so.2.5.1
> libGLEW.so.1.10             node_modules
> libGLEW.so.1.10.0           pkgconfig
> libraylib.so                python3.10
> ```
> 
> It seems like all the newest library versions have been installed.

Well, I can see a big issue right here. Remember how `apt` says you have lib**c**sfml(blabla)**2.5**? Well, here you *do* have lib**sfml**(blabla)2.5... and you also have lib**sfml**/lib**c**sfml(blabla)**2.2**.
Try checking for the lib**c**sfml2.5 files in `/usr/lib` as well. What's strange is that normally installed packages don't go in `usr/local/<name>`, they go in `/usr/<name>`. I think something you've downloaded has installed lib**sfml**/lib**c**sfml2.2 as a dependency, and you might need to uninstall it.

> Not sure what the next steps are in solving this, but I don't believe it is an issue on my end.
> ### I would recommend that you try to reproduce my errors, I would boot up a Linux Mint VM, and just follow the steps I did and observe the errors.

I don't have the time for that at the moment unfortunately.

**Comment by therealbluepandabear** [comment]
Well I'm gonna try and boot up a VM of my own and install the packages that you've linked above manually, then I'll see if I can reproduce the error. I'll get back soon.

**Comment by ichordev** [comment]
> Well I'm gonna try and boot up a VM of my own and install the packages that you've linked above manually -- one-by-one, then I'll see if I can reproduce the error. I'll get back soon.

Good luck! Keep in mind that if you install something that uses SFML 2.2 again you might end up experiencing the same issue.

Honestly I'm disappointed that neither CSFML nor SFML seem to have a function to get the linked version. It's an essential feature when troubleshooting issues like this.

**Comment by therealbluepandabear** [comment]
After successfully booting up the VM, installing the packages manually, I get a new error:

```
object.Exception@source/app.d(21): Fatal error(s) encountered whilst calling `loadSFML()` function: ["Error: libcsfml-system.so, Message: libcsfml-system.so: cannot open shared object file: No such file or directory", "Error: libcsfml-system.so.2, Message: libcsfml-system.so.2: cannot open shared object file: No such file or directory", "Error: libcsfml-system.so.2.0, Message: libcsfml-system.so.2.0: cannot open shared object file: No such file or directory"]
```

This is a fatal error.

**Comment by ichordev** [comment]
> installing the packages manually

Manually via `apt` or by compiling & installing them yourself? If you haven't tried compiling yourself, I'd say it's worth a shot. Really looks like something is up with your distro's packages... :grimacing: 

> ```
> object.Exception@source/app.d(21): Fatal error(s) encountered whilst calling `loadSFML()` function: 
> ["Error: libcsfml-system.so, Message: libcsfml-system.so: cannot open shared object file: No such file or directory", 
> "Error: libcsfml-system.so.2, Message: libcsfml-system.so.2: cannot open shared object file: No such file or directory", 
> "Error: libcsfml-system.so.2.0, Message: libcsfml-system.so.2.0: cannot open shared object file: No such file or directory"]
> ```
> 
> This is a fatal error.

Well the libraries were somewhere it couldn't find them, then. :woman_shrugging: 

> Then I installed `libcsfml-dev` once again (I had nothing to lose) and got this error:
> 
> ```
> object.Exception@source/app.d(21): Fatal error(s) encountered whilst calling `loadSFML()` function:
>  ["Error: Missing Symbol, Message: sfRenderTexture_createWithSettings", 
> "Error: Missing Symbol, Message: sfRenderTexture_getMaximumAntialiasingLevel", "Error: Missing Symbol, Message: sfText_getLineSpacing", 
> "Error: Missing Symbol, Message: sfText_getLineSpacing"]
> ```
> 
> Any thoughts?

Same missing symbols. Please check the libcsfml libraries (not the libsfml ones like you did last time) with `nm -gD <filename>`. Try doing also `nm -gD <filename> | grep <symbol>` with those missing symbols you keep seeing:
`sfRenderTexture_createWithSettings`, `sfRenderTexture_getMaximumAntialiasingLevel`, `sfText_getLineSpacing`
This should help us figure out whether it's definitely your distro's packages or not.

**Comment by ichordev** [comment]
Just wanted to add, after looking at the CSFML release changelogs I found some relevant fixes:

## [CSFML 2.5.1](https://github.com/SFML/CSFML/releases/tag/2.5.1)
- Add missing sfTexture_updateFromTexture function implementation (https://github.com/SFML/CSFML/issues/141)
- Correct sfRenderTexture_createWithSettings function signature (https://github.com/SFML/CSFML/pull/137)

## [CSFML 2.5](https://github.com/SFML/CSFML/releases/tag/2.5)
- sfText_getLineSpacing is not properly declared in Text.h

It's also worth mentioning that in CSFML 2.5 `sfRenderTexture_getMaximumAntialiasingLevel` is missing `CSFML_GRAPHICS_API` in its signature, meaning that you probably need CSFML 2.5.1 for it to work properly.

Again, I'd recommend downloading the source of CSFML 2.5.1 and compiling/installing it yourself.

**Comment by therealbluepandabear** [comment]
I'll review this situation soon.
