### ISSUE TITLE
[Feature request] Add base class types such as `sf::Drawable` / `sf::RenderTarget` so it's easier to work with these bindings for D

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#8]
Hello 👋

Since this is a CSFML binding and C is not an object oriented language, it's missing some very useful base types such as `cf::Drawable` / `cf::RenderTarget` (the tutorial I am following through requires the use of these types), consider adding some wrappers for base class types so this binding is easier to work with. 

For example the C# bindings for SFML have an interface for `Drawable` (the equivalent of `cf::Drawable`):

![image](https://user-images.githubusercontent.com/50536495/207484772-a52b6892-c7c9-45a4-b794-2b229b2dce4c.png)

You may want to take inspiration from how it was implemented in SFML.Net: 

`Drawable` interface: https://github.com/SFML/SFML.Net/blob/43926e92e24750f364abbb2455b5033e3c226999/src/SFML.Graphics/Drawable.cs

`RenderTarget` interface: https://github.com/SFML/SFML.Net/blob/43926e92e24750f364abbb2455b5033e3c226999/src/SFML.Graphics/RenderTarget.cs

The Rust bindings as well have a `Drawable` base type: https://github.com/jeremyletang/rust-sfml/blob/80d3cf0f5d20224d8948fc9e25a471a6318436bd/src/graphics/drawable.rs ... and `RenderTarget` base type https://github.com/jeremyletang/rust-sfml/blob/261e1f51a40f8fc03aa01bc4333d2041776818a0/src/graphics/render_target.rs

As you can see most bindings to object oriented languages seem to implement these base types.

(There are probably some more base types, but those two seem to be the most important.)

For the book I am reading, this is the method I need to implement:

```C++
void Window::Draw(sf::Drawable&l_drawable){
    m_window.draw(l_drawable);
}
```

As you can see it's currently impossible as the library has no `sfDrawable` type. Since D is an object oriented language I believe it would be amazing if you guys could add a D equivalent for these base types so it's easier to work through SFML tutorials and create more object oriented syntax.

Again, not sure how hard it is but just a suggestion 🙂 

I do not want to pressure anyone into adding new features that may be difficult since this is purely a volunteer project.

 You've already done excellent work on these bindings so far, but this will be the icing on the cake.

**Comment by ichordev** [comment]
Thanks for your suggestion.
First of all, "easier to work with these bindings for D" assumes that everyone who uses D writes object-oriented code with classes. Procedural D code is very common. The code example you gave should be completely possible to write in D without the `sf::Drawable` abstract base class:
```d
class Window{
  void Draw(T)(ref T l_drawable){
    m_window.draw(l_drawable);
  }
}
```
Object-oriented code turns into procedural machine code once it's compiled, so any C++ code that's bindable to C should be able to be turned into object-oriented code again on your end with a wrapper with a little bit of time. As you mentioned, bindbc-sfml is a binding to CSFML. If CSFML lacks functionality that SFML has (like the functions from `sf::RenderTarget`), then the issue is with CSFML.

Making bindbc-sfml into a mixed CSFML/SFML binding would be a mess and could have irreconcilable consequences. The SFML.Net binding you referenced there is official, but it's unclear *how* the library binds to CSFML, so it's not a great example. rust-sfml is just a direct SFML binding.

Back when bindbc-sfml was created, D's C++ interoperability was significantly lacking. Additionally, there was no built-in way to allocate class instances in BetterC (i.e. `new`), meaning you would have to create a fake class instance and then make it point to a user-allocated piece of memory. Nowadays this is possible:
```d
extern(C++) class MyClass{ int x; }

extern(C) void main(){
  scope a = new MyClass();
  a.x = 10;
}
```
`extern(C++)` classes can be allocated in BetterC as `scope` variables.

In the future I do plan to rewrite bindbc-sfml to be a direct binding to SFML. bindbc-sdl will be getting updated much sooner, and SDL2 can already do most of the same things as SFML, so SFML's rewrite will probably come after all the other bindbc libraries are upgraded.

**Comment by mdparker** [comment]
> I see the CSFML library as a base that should/can be extended for each language.

Exactly! And the point of bindbc-sfml is that it is a direct binding to CSFML that provides the base for D. My intent with all of my C bindings is that they be no more than bindings; they don't add anything to the API of the library to which they bind. I think this is an important concept. It reduces the maintenance burden for the maintainer, as you don't need any new or additional documentation (the C library's documentation serves equally well for the binding), and there's no additional API to maintain. 

However, anyone can use these bindings in turn to, as you suggest, extend the functionality of the C library by providing a wrapper. 

> you said I could create a wrapper, could you please tell me more about this?

A wrapper provides a different interface atop an existing one, usually in a different language. CSFML itself is a wrapper of SFML. So, for example, given a library `clib` with a function like `int clib_register_name(const char* name)`, you might write a D function like this:

```d
module clibd;
import clib;  // A hypothetical binding to clib
mport std.string : toStringz;

bool registerName(string name) 
{
    return clib_register_name(name.toStringz) != 0;
}
```

Your `registerName` _wraps_ the C function and provides a D interface for it.

The `sf::Drawable` can be replicated in D as a template as @ichordev suggested, or perhaps an abstract class or interface (depending on what it does).

**Comment by ichordev** [comment]
> The first D example you have given is more of a band-aid than a solution because it allows me to pass any type.

Just add a template constraint if you care about that. It's not really necessary at all, but if you think you'll end up passing the wrong type then you should.
```d
class Window{
  void Draw(T)(ref T l_drawable)
  if(isDrawable!T){
    m_window.draw(l_drawable);
  }
}
```
> Perhaps you guys could work on a tutorial series for these bindings.

No. These are bindings, you use them the same way as the library they're binding. I would recommend you look up a CSFML-specific tutorial if CSFML is really missing these base classes. That said, maybe you're not meant to inherit from those classes in the first place if their methods aren't in CSFML?

**Comment by therealbluepandabear** [comment]
Thanks guys. I'll just stick with the template fix and continue with the book.

Its great that you plan on adding C++ SFML bindings, its good to have goals and ambitions. I look forward to seeing C++ SFML D bindings sometime in the future.

**Comment by therealbluepandabear** [comment]
Trying out your code, I now see that it's not possible as there is no `draw()` method for the window. Thanks anyways.

**Comment by ichordev** [comment]
> Trying out your code, I now see that it's not possible as there is no `draw()` method for the window. I'll just have to settle for multiple duplicated methods or an `accessWindow()` function. E.g.:
> 
> ```d
> void drawSprite(sfSprite* sprite) {
>     m_window.sfRenderWindow_drawSprite(sprite, null);
> }
> ```

My mistake, yeah you can make an overload of `Draw` for each different drawable you want it to wrap.

> Or:
> 
> ```d
> sfRenderWindow* accessWindow() {
>     return m_window;
> }
> ```

Why not `alias this`? ;)

> Since D interoperability with C++ has improved and seems to be stable, I might make OOP D bindings to C++ SFML in the future as well when I am more experienced, that seems like a fun project.

I wouldn’t recommend doing it without some pretty extensive knowledge of what mangling is, how linking and static vs dynamic libraries work, etc. Unless you like painstakingly translating C++ code and dealing with obtuse compiler errors, I’d say focus on making stuff for yourself. ;P

> there are no base types in that specific bindings, similar to this one.

Wrong.
https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/drawable.d
https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/rendertarget.d

> The Rust bindings are also CSFML bindings, not direct C++ SFML bindings.

Right, I got a bit confused. CSFML is written in C++ apparently, but only uses C-compatible features and `extern "C"`

**Comment by therealbluepandabear** [comment]
> > Trying out your code, I now see that it's not possible as there is no `draw()` method for the window. I'll just have to settle for multiple duplicated methods or an `accessWindow()` function. E.g.:
> > ```d
> > void drawSprite(sfSprite* sprite) {
> >     m_window.sfRenderWindow_drawSprite(sprite, null);
> > }
> > ```
> 
> My mistake, yeah you can make an overload of `Draw` for each different drawable you want it to wrap.
> 
> > Or:
> > ```d
> > sfRenderWindow* accessWindow() {
> >     return m_window;
> > }
> > ```
> 
> Why not `alias this`? ;)
> 
> > Since D interoperability with C++ has improved and seems to be stable, I might make OOP D bindings to C++ SFML in the future as well when I am more experienced, that seems like a fun project.
> 
> I wouldn’t recommend doing it without some pretty extensive knowledge of what mangling is, how linking and static vs dynamic libraries work, etc. Unless you like painstakingly translating C++ code and dealing with obtuse compiler errors, I’d say focus on making stuff for yourself. ;P
> 
> > there are no base types in that specific bindings, similar to this one.
> 
> Wrong. https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/drawable.d https://github.com/Jebbs/DSFML/blob/master/src/dsfml/graphics/rendertarget.d
> 
> > The Rust bindings are also CSFML bindings, not direct C++ SFML bindings.
> 
> Right, I got a bit confused. CSFML is written in C++ apparently, but only uses C-compatible features and `extern "C"`

Thanks. Haven't gotten to `alias this` yet (it's further down in the book I am reading).

**Comment by therealbluepandabear** [comment]
Hi,

I will be working on my own OOP wrapper library for these bindings soon.

My goal is for it to match the C++ SFML syntax as close as possible.

Regards,
thebluepandabear
